version: '3.7'

services:
  postgres:
    image: postgres
    container_name: bookshop
    networks:
      - bookshop-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0211
      POSTGRES_DB: bookshop_db
    ports:
      - "5050:5432"

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8585:8585"
    restart: always
    networks:
      - bookshop-network

  quarkus-app:
    image: quarkus/fido-bookshop-project-jvm
    container_name: bookshop-project
    networks:
      - bookshop-network
    ports:
      - "9090:8080"
    environment:
      DB_HOST: bookshop
    depends_on:
      - postgres

networks:
  bookshop-network:
    external: true